### ISSUE TITLE
bug en el header

### ISSUE THREAD

**Issue by dmarcob** [STW-Enjoyers/frontend#37]
Estoy logeado en el sistema.
Cuando las opciones no están colapsadas se muestra el desplegable con las opciones de perfil.
Sin embargo, cuando hago la pantalla pequeña y las opciones colapsan, me ocurre que se muestra 'Iniciar sesion', en vez del desplegable con las opciones del perfil :0

Adjunto gif
![bug](https://user-images.githubusercontent.com/45805074/167694027-2a8bdf73-a152-4f83-b99b-3057a61c4f8e.gif)

**Comment by 717044** [comment]
Solucionado en local. En el próximo PR se aplicará el cambio.
