### ISSUE TITLE
Header options disappear

### ISSUE THREAD

**Issue by dmarcob** [STW-Enjoyers/frontend#8]
With a medium screen size, all buttons in header disappear.
Some text in home page is affected too.
![Captura de pantalla de 2022-04-10 20-24-00 (1)](https://user-images.githubusercontent.com/45805074/162634043-51e7f9d0-b124-4d79-a701-a45978362ac1.png)

**Comment by 717044** [comment]
Trying to replicate it, but I can't. Are you using Google Chrome?
Maybe the new changes I did in my branch solved it. I will keep an eye on this issue.
